backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: "Marcas"
    name: "brands"
    folder: "content/brands"
    slug: "{{fields.title}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}"
    editor:
     preview: false
    fields:
      - { label: "Nombre Marca", name: "title", widget: "string" }
      - { label: "Logo Marca", name: "brandLogo", widget: "image" }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "brands",
        }
      - label: "Categorias"
        name: "categories"
        widget: "list"
        summary: "{{fields.category}}"
        field: { label: Categoria, name: category, widget: string }
      - label: "Fotos"
        name: "gallery"
        widget: "list"
        required: false
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }